version: '3.8'
services:
  app:
    container_name: app
    build:
      context: ./Awesome
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: admin
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Abcd@1234"
    ports:
      - "1433:1433"
  sonarqube:
    image: sonarqube:community
    depends_on:
      - sona-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sona-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  sona-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: