version: '3.8'
services:
  app:
    container_name: app
    build:
      context: ./Awesome
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: admin
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Abcd@1234"
    ports:
      - "1433:1433"